# https://github.com/rsp/travis-hello-modern-cpp/blob/master/.travis.yml

dist: xenial
language:
  - cpp
  - python # python is only used to build docs

python:
  - "3.6"

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update
  - sudo ./install-apt.sh
  - mkdir build
  - cd build
  - cmake ..

install: "pip install --user sphinx sphinx_rtd_theme sphinxcontrib-bibtex"

script:
  - make # build c/c++
  - make test # run all the test
  - cd ../docs && make html  # build doc

before_deploy: touch build/html/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable in travis portal
  keep-history: true
  local-dir: docs/build/html
  on:
    branch:
      - master  # updates from this branch will trigger deploy
      - feng
