# https://github.com/rsp/travis-hello-modern-cpp/blob/master/.travis.yml

dist: xenial
language:
  - cpp
  - python # python is only used to build docs

env:
  - AWNN_ROOT=${TRAVIS_BUILD_DIR}

python:
  - "3.6"

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update
  - sudo ./install-apt.sh
  - mkdir build
  - cd build
  - cmake .. -DIS_CI_BUILD=on -DUSE_OPENBLAS=on

install: "pip install --user sphinx sphinx_rtd_theme sphinxcontrib-bibtex"

script:
  - cd ${AWNN_ROOT}/data/cifar10
  - ./get_cifar10.sh
  - cd ${AWNN_ROOT}/build
  - make # build c/c++
  - make test # run all the test
  - cd ${AWNN_ROOT}/docs && make html  # build doc

before_deploy: touch build/html/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable in travis portal
  keep-history: true
  local-dir: docs/build/html
  on:
    branch:
      - master  # updates from this branch will trigger deploy
      - feng
