# https://github.com/rsp/travis-hello-modern-cpp/blob/master/.travis.yml

dist: xenial
language: cpp
compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

#install:
  #- "[ $CXX = g++ ] && export CXX=g++-6 || true"
  #- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

script:
  - make
