//
// Created by cmgoebel on 4/29/19.
//
#include "memory.h"


static long TOTAL_TENSOR_ALLOC_HOST = 0;
static long TOTAL_TENSOR_ALLOC_DEVICE = 0;
static long TOTAL_TENSOR_DEALLOC_HOST = 0;
static long TOTAL_TENSOR_DEALLOC_DEVICE = 0;

long INC_TOTAL_TENSOR_ALLOC_HOST() {
  return ++TOTAL_TENSOR_ALLOC_HOST;
}
long INC_TOTAL_TENSOR_ALLOC_DEVICE() {
  return ++TOTAL_TENSOR_ALLOC_DEVICE;
}
long INC_TOTAL_TENSOR_DEALLOC_HOST() {
  return ++TOTAL_TENSOR_DEALLOC_HOST;
}
long INC_TOTAL_TENSOR_DEALLOC_DEVICE() {
  return ++TOTAL_TENSOR_DEALLOC_DEVICE;
}


long GET_TOTAL_TENSOR_ALLOC_HOST() {
  return TOTAL_TENSOR_ALLOC_HOST;
}
long GET_TOTAL_TENSOR_DEALLOC_HOST() {
  return TOTAL_TENSOR_DEALLOC_HOST;
}
long GET_TOTAL_TENSOR_ALLOC_DEVICE() {
  return TOTAL_TENSOR_ALLOC_DEVICE;
}
long GET_TOTAL_TENSOR_DEALLOC_DEVICE() {
  return TOTAL_TENSOR_DEALLOC_DEVICE;
}
